services:
 - docker
before_install:
  - make lint
install:
  - make build
  - make run
  - docker run -d -p 127.0.0.1:3142:3142 --name apt-cacher-ng apt-cacher-ng 
script:
  - docker ps | grep -q apt-cacher-ng
